# ===============================================
#  DEVELOPMENT SETTINGS (DEV)
# ===============================================

# --- Database ---
spring.datasource.url=jdbc:postgresql://localhost:5435/personal_finance_db
spring.datasource.username=admin
spring.datasource.password=hkG4563

# --- JPA/Hibernate ---
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.format_sql=true

# --- Connection Pool ---
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.idle-timeout=120000
spring.datasource.hikari.max-lifetime=300000
spring.datasource.hikari.connection-timeout=20000

# --- Logging ---
logging.level.org.springframework=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.com.zaxxer.hikari=DEBUG
logging.level.org.flywaydb=DEBUG